# General settings
dist: trusty
sudo: false
language: node_js
node_js:
  - "lts/*"
cache: false
notifications:
  email: false
branches:
  only:
    - master
    - develop

# Build stages
stages:
  - name: build
  - name: test
  - name: release
    if: branch = master

# Build jobs
jobs:
  include:

    - stage: build
      before_install:
        - npm install -g npm
      install:
        - npm ci
      script:
        - npm run build:library
        - npm run build:demo

    - stage: test
      before_install:
        - npm install -g npm
      install:
        - npm ci
      script:
        - npm run test:library
      after_success:
        - npm run test:library:coverage

    - stage: release
      before_install:
        - npm install -g npm
        # Clone the whole repository because we also need the develop branch for releasing (Travis only gives us the master by default)
        - git clone "https://github.com/$TRAVIS_REPO_SLUG.git" "$TRAVIS_REPO_SLUG";
        - cd "$TRAVIS_REPO_SLUG";
        - git checkout -qf "$TRAVIS_COMMIT";
        #  Fix Travis CI issue of detached heads in git
        - git checkout master
      install:
        - npm ci
      before_deploy:
        # Login to Git to be able to make commits (required by automatic-release)
        - git config --global user.name "dominique-mueller";
        - git config --global user.email "dominique.m.mueller@gmail.com";
        - git config credential.helper "store --file=.git/credentials";
        - echo "https://$GH_TOKEN:@github.com" > .git/credentials;
        # Do release
        - npm run release
        - npm run build:library
        - npm run release:complete
        # Publish the dist folder
        - cd dist/angular-notifier
      deploy:
        provider: npm
        email: dominique.m.mueller@gmail.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
      after_deploy:
        - cd ../..
